version: 2

sources:
  - name: bronze
    description: "Raw data loaded from football API"
    database: football_stats_db
    schema: bronze
    tables:
      - name: matches
        description: "All football matches data"
        columns:
          - name: id
            description: Unique match identifier
            tests:
              - unique
              - not_null
          - name: status
            description: Match status
            tests:
              - not_null
              - accepted_values:
                  values: ['FINISHED', 'SCHEDULED', 'IN_PLAY', 'PAUSED', 'TIMED', 'POSTPONED', 'CANCELLED', 'SUSPENDED', 'AWARDED']
          - name: '"homeTeam_id"'
            description: Home team ID
            tests:
              - not_null
          - name: '"awayTeam_id"'
            description: Away team ID
            tests:
              - not_null
      - name: competitions
        description: "Details of football competitions"